# Generated by Django 4.1.4 on 2022-12-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework3', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
