# Generated by Django 4.1.4 on 2022-12-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework3', '0004_remove_user_is_customer_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
