# Generated by Django 4.1.4 on 2022-12-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework3', '0006_remove_user_is_customer_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
