# Generated by Django 4.1.4 on 2022-12-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework3', '0008_questions_remove_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_pic',
        ),
    ]
